### ISSUE TITLE
How can I know the file path of the thumb?

### ISSUE THREAD

**Issue by tudows** [thumbcacheviewer/thumbcacheviewer#1]

**Comment by tudows** [comment]
I can get the thumb's info, but I want to which file the thumb represent

**Comment by thumbcacheviewer** [comment]
There's two way you can get the original path of the thumbnail. You can map the entries to the files on the system in which the thumbcache database was created, or you can map the entries to the paths that are stored in the Windows Search database (Windows.edb). The Windows Search database is located in "C:\ProgramData\Microsoft\Search\Data\Applications\Windows". To be able to access it on a live system, you'll need to stop the Windows Search service.

The first thing you'll need to do is to load a thumbcache database into Thumbcache Viewer. Once that's complete, go to the "Tools" menu and select "Map File Paths...". In this new window you can either scan the system you're on for the original file paths, or you can load the Windows.edb database to scan it for the original file paths.

Hope this helps.

**Comment by tudows** [comment]
So, I think that can I get a video file's thumbnail generated by system? I use the “ExtractIcon” api and I can only get the video file's common system file instead of the thumbnail generated by system.

**Comment by thumbcacheviewer** [comment]
ExtractIcon isn't going to work. You'll need to deal with it in another way. Refer to this post and its top answer: https://stackoverflow.com/questions/19523599/how-to-get-thumbnail-of-file-using-the-windows-api

I've never used the code that was mentioned in that post, so I don't think I'll be of much help, but hopefully it'll guide you in the right direction.

**Comment by zhengran14** [comment]
thank you very much
