### ISSUE TITLE
Contact for test data

### ISSUE THREAD

**Issue by emmanuelgiguet** [thumbcacheviewer/thumbcacheviewer#12]
Is it possible to get access to various thumnail files from different version of OS in order to better understand the variations ? I belong to a research team in cybersecurity and a former forensics legal expert.
Thank you for your work !

**Comment by erickutcher** [comment]
I don't have any test files at the moment. They way I got them was by downloading from open directories and on file sharing networks like Soulseek. That's not the easiest thing to do anymore and finding people that are running/hosting older systems like Vista is next to impossible. The best solution would be to run a virtual machine and install the various different Windows systems. You'll want Vista, 7, 8, 8.1, 10/11. 10 and 11 are exactly the same as far as I'm aware.

**Comment by emmanuelgiguet** [comment]
Thank you for your answer. I will try to find a way to build the dataset.
