### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by fire-eggs** [thumbcacheviewer/thumbcacheviewer#7]
Nice program. I wrote it up for the [DarkThumbs wiki](https://github.com/L0garithmic/DarkThumbs/wiki/Using-Thumbcache-Viewer-to-force-a-rebuild-of-specific-thumbnails).

**Comment by thumbcacheviewer** [comment]
I appreciate that. Thank you. The Remove Selected menu option only removes the entry that's listed in Thumbcache Viewer. It doesn't actually remove it from the cache itself. Only real way to rebuild the cache is to use Disk Cleanup.

**Comment by fire-eggs** [comment]
I guess it was too good to be true ... Thank you, tho, I've learned something new today!
