### ISSUE TITLE
No network path support

### ISSUE THREAD

**Issue by fire-eggs** [thumbcacheviewer/thumbcacheviewer#8]
This code in wnd_proc_scan.cpp disables network folder support:
```
// We need to have at least the drive path. Example: "C:\"
if ( g_filepath[ 1 ] == L':' && g_filepath[ 2 ] == L'\\' )
```

Windows Explorer has thumbnails for a network path and I can browse for that path via the browse-for-folder dialog, but the app won't accept it as "valid".

![image](https://user-images.githubusercontent.com/9809727/132955130-a3d03bd5-3f5f-42ba-93a4-609991263572.png)

**Comment by thumbcacheviewer** [comment]
One of the functions that's needed to map entries is called [GetVolumeNameForVolumeMountPoint](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getvolumenameforvolumemountpointw). It requires a drive letter and so a network folder isn't going to work. If the actual location of the network folder is on the same computer, then a scan of that location will work, but if it's on another computer, then it won't. It's not possible to retrieve the Volume GUID of another computer's drive. And that's one of the input's for the mapping algorithm.

Does your network folder also have a hidden Thumbs.db file in it? Windows uses those files for thumbnails in network folders.

**Comment by fire-eggs** [comment]
Understood. I figured there probably was a good reason!
